services:
  cms:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: go run services/cms/main.go -b 0.0.0.0

  discovery:
    build: .
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
    command: go run services/discovery/main.go -b 0.0.0.1

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
volumes:
  postgres-db: